// Generated by uniffi-bindgen-react-native
#include "entropystudio.h"
#include "generated/entropystudio_ffi.hpp"

namespace entropystudio {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeEntropystudioFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}