// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "entropystudio.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "EntropyStudio.h"

@interface Entropystudio : NSObject <NativeEntropystudioSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Entropystudio : NSObject <RCTBridgeModule>
#endif

@end