import {
  Bip39PassphraseState,
  CardHashMethod,
  CardInputMethod,
  DirectCardStep as GeneratedDirectCardStep,
  DirectDiceCalculationTermKind as GeneratedDirectDiceCalculationTermKind,
  DiceFinalStep,
  DiceInputMethod as GeneratedDiceInputMethod,
  DiceRollMethod,
  DirectDiceMethod as GeneratedDirectDiceMethod,
  DirectDiceStep as GeneratedDirectDiceStep,
  HashedCardInstruction,
  KeyDerivationBranchRole as GeneratedKeyDerivationBranchRole,
  KeyDerivationNetworkKind as GeneratedKeyDerivationNetworkKind,
  KeyDerivationPathHelpKind as GeneratedKeyDerivationPathHelpKind,
  KeyDerivationValidationKind as GeneratedKeyDerivationValidationKind,
  KeyDerivationVisiblePathValidationKind as GeneratedKeyDerivationVisiblePathValidationKind,
  NumberBaseFormat as GeneratedNumberBaseFormat,
  PrivateKeyFormat as GeneratedPrivateKeyFormat,
  PrivateKeyInputStatus as GeneratedPrivateKeyInputStatus,
  SeedPhraseInputMethod as GeneratedSeedPhraseInputMethod,
  SeedPhraseStatus as GeneratedSeedPhraseStatus,
  analyzeNumberBaseInput,
  bip39EntropyBits,
  bip39PassphraseAutocomplete,
  bip39PassphraseKeyAllowed,
  bip39PassphraseSpaceAllowed,
  bip39PassphraseState,
  cardKeyAllowed,
  cardTranscriptToEntropy,
  diceMethodInfo,
  directCardState,
  directDiceCalculations,
  directDiceInputState,
  directDiceState,
  diceRollsToEntropy,
  entropyToMnemonic,
  EntropyStudioError_Tags,
  EntropySyncSource as GeneratedEntropySyncSource,
  formatDiceTranscript,
  hashedCardState,
  hashedDiceState,
  keyDerivationAddressBenchmarkMilliseconds,
  keyDerivationAddressEstimateMilliseconds,
  keyDerivationAdvancedState,
  keyDerivationProjectAdvancedPath,
  keyDerivationVisiblePathState,
  lifehashFromFingerprint,
  mnemonicToEntropy,
  mnemonicToMasterFingerprint,
  mnemonicToMasterXprv,
  mnemonicToSeed,
  normalizeCardToken,
  normalizeDirectCardTranscript,
  numberBaseCalculations,
  numberBaseEntropy,
  privateKeyEntropy,
  privateKeyInputState,
  privateKeyKeyAllowed,
  privateKeyMaterial,
  seedPhraseAutocomplete,
  seedPhraseKeyAllowed,
  seedPhraseNumbersToWords,
  seedPhraseSpaceAllowed,
  seedPhraseState,
  seedPhraseWordsToNumbers,
  seedQrData,
  synchronizeEntropy,
  translateSeedNumberIndices,
} from 'entropystudio';

export const DirectDiceMethod = {
  Bitbox: GeneratedDirectDiceMethod.Bitbox,
  D8D16: GeneratedDirectDiceMethod.D8d16,
} as const;

export const DiceInputMethod = {
  Bitbox: GeneratedDiceInputMethod.Bitbox,
  Coldcard: GeneratedDiceInputMethod.Coldcard,
  Coleman: GeneratedDiceInputMethod.Coleman,
  D8D16: GeneratedDiceInputMethod.D8d16,
} as const;

export const EntropySyncSource = {
  CardsDirect: GeneratedEntropySyncSource.CardsDirect,
  CardsHashedAscii: GeneratedEntropySyncSource.CardsHashedAscii,
  CardsHashedColeman: GeneratedEntropySyncSource.CardsHashedColeman,
  DiceBitbox: GeneratedEntropySyncSource.DiceBitbox,
  DiceColdcard: GeneratedEntropySyncSource.DiceColdcard,
  DiceColeman: GeneratedEntropySyncSource.DiceColeman,
  DiceD8D16: GeneratedEntropySyncSource.DiceD8d16,
  NumberBaseBase4: GeneratedEntropySyncSource.NumberBaseBase4,
  NumberBaseBase8: GeneratedEntropySyncSource.NumberBaseBase8,
  NumberBaseBase32: GeneratedEntropySyncSource.NumberBaseBase32,
  NumberBaseBase64: GeneratedEntropySyncSource.NumberBaseBase64,
  NumberBaseBin: GeneratedEntropySyncSource.NumberBaseBin,
  NumberBaseHex: GeneratedEntropySyncSource.NumberBaseHex,
  PrivateKeyBrainWallet: GeneratedEntropySyncSource.PrivateKeyBrainWallet,
  PrivateKeyBrainWalletTrimmed: GeneratedEntropySyncSource.PrivateKeyBrainWalletTrimmed,
  PrivateKeyHex: GeneratedEntropySyncSource.PrivateKeyHex,
  PrivateKeyMiniKey: GeneratedEntropySyncSource.PrivateKeyMiniKey,
  PrivateKeyWif: GeneratedEntropySyncSource.PrivateKeyWif,
  SeedNumbers: GeneratedEntropySyncSource.SeedNumbers,
  SeedWords: GeneratedEntropySyncSource.SeedWords,
} as const;

export const SeedPhraseInputMethod = {
  Words: GeneratedSeedPhraseInputMethod.Words,
  Numbers: GeneratedSeedPhraseInputMethod.Numbers,
} as const;

export const PrivateKeyFormat = {
  Wif: GeneratedPrivateKeyFormat.Wif,
  Hex: GeneratedPrivateKeyFormat.Hex,
  MiniKey: GeneratedPrivateKeyFormat.MiniKey,
  BrainWallet: GeneratedPrivateKeyFormat.BrainWallet,
} as const;

export const PrivateKeyInputStatus = {
  Empty: GeneratedPrivateKeyInputStatus.Empty,
  Prefix: GeneratedPrivateKeyInputStatus.Prefix,
  Incomplete: GeneratedPrivateKeyInputStatus.Incomplete,
  Invalid: GeneratedPrivateKeyInputStatus.Invalid,
  Excess: GeneratedPrivateKeyInputStatus.Excess,
  Ready: GeneratedPrivateKeyInputStatus.Ready,
} as const;

export const SeedPhraseStatus = {
  Remaining: GeneratedSeedPhraseStatus.Remaining,
  Extra: GeneratedSeedPhraseStatus.Extra,
  ChooseFinal: GeneratedSeedPhraseStatus.ChooseFinal,
  Ready: GeneratedSeedPhraseStatus.Ready,
  FinalPrefix: GeneratedSeedPhraseStatus.FinalPrefix,
  NoFinalPrefix: GeneratedSeedPhraseStatus.NoFinalPrefix,
  InvalidWord: GeneratedSeedPhraseStatus.InvalidWord,
  InvalidNumber: GeneratedSeedPhraseStatus.InvalidNumber,
  ChecksumInvalid: GeneratedSeedPhraseStatus.ChecksumInvalid,
} as const;

export const DirectCardStep = {
  Word: GeneratedDirectCardStep.Word,
  Final: GeneratedDirectCardStep.Final,
  Correction: GeneratedDirectCardStep.Correction,
  Complete: GeneratedDirectCardStep.Complete,
} as const;

export const DirectDiceStep = {
  BitboxDie: GeneratedDirectDiceStep.BitboxDie,
  BitboxCoin: GeneratedDirectDiceStep.BitboxCoin,
  BitboxFinalWord: GeneratedDirectDiceStep.BitboxFinalWord,
  D8D16WordD8: GeneratedDirectDiceStep.D8d16WordD8,
  D8D16WordD16First: GeneratedDirectDiceStep.D8d16WordD16First,
  D8D16WordD16Second: GeneratedDirectDiceStep.D8d16WordD16Second,
  D8D16ChecksumD8: GeneratedDirectDiceStep.D8d16ChecksumD8,
  D8D16ChecksumD16: GeneratedDirectDiceStep.D8d16ChecksumD16,
  D8D16ChecksumCoin: GeneratedDirectDiceStep.D8d16ChecksumCoin,
  D8D16Correction: GeneratedDirectDiceStep.D8d16Correction,
  D8D16Complete: GeneratedDirectDiceStep.D8d16Complete,
} as const;

export const KeyDerivationBranchRole = {
  Receive: GeneratedKeyDerivationBranchRole.Receive,
  Change: GeneratedKeyDerivationBranchRole.Change,
  Custom: GeneratedKeyDerivationBranchRole.Custom,
} as const;

export const KeyDerivationNetworkKind = {
  Mainnet: GeneratedKeyDerivationNetworkKind.Mainnet,
  Testnet: GeneratedKeyDerivationNetworkKind.Testnet,
  CustomMainnetAddresses: GeneratedKeyDerivationNetworkKind.CustomMainnetAddresses,
  Invalid: GeneratedKeyDerivationNetworkKind.Invalid,
} as const;

export const KeyDerivationPathHelpKind = {
  Exact: GeneratedKeyDerivationPathHelpKind.Exact,
  MultipleBranches: GeneratedKeyDerivationPathHelpKind.MultipleBranches,
  MultipleIndexes: GeneratedKeyDerivationPathHelpKind.MultipleIndexes,
  MultipleBranchesAndIndexes: GeneratedKeyDerivationPathHelpKind.MultipleBranchesAndIndexes,
  Invalid: GeneratedKeyDerivationPathHelpKind.Invalid,
} as const;

export const KeyDerivationValidationKind = {
  Valid: GeneratedKeyDerivationValidationKind.Valid,
  AccountPrefix: GeneratedKeyDerivationValidationKind.AccountPrefix,
  BranchStart: GeneratedKeyDerivationValidationKind.BranchStart,
  BranchRange: GeneratedKeyDerivationValidationKind.BranchRange,
  AddressStart: GeneratedKeyDerivationValidationKind.AddressStart,
  AddressRange: GeneratedKeyDerivationValidationKind.AddressRange,
} as const;

export const KeyDerivationVisiblePathValidationKind = {
  Valid: GeneratedKeyDerivationVisiblePathValidationKind.Valid,
  Root: GeneratedKeyDerivationVisiblePathValidationKind.Root,
  Index: GeneratedKeyDerivationVisiblePathValidationKind.Index,
  MissingComponents: GeneratedKeyDerivationVisiblePathValidationKind.MissingComponents,
  MissingAccount: GeneratedKeyDerivationVisiblePathValidationKind.MissingAccount,
  BranchStart: GeneratedKeyDerivationVisiblePathValidationKind.BranchStart,
  BranchRange: GeneratedKeyDerivationVisiblePathValidationKind.BranchRange,
  AddressStart: GeneratedKeyDerivationVisiblePathValidationKind.AddressStart,
  AddressRange: GeneratedKeyDerivationVisiblePathValidationKind.AddressRange,
} as const;

export {
  CardHashMethod,
  CardInputMethod,
  GeneratedDirectDiceCalculationTermKind as DirectDiceCalculationTermKind,
  DiceFinalStep,
  DiceRollMethod,
  HashedCardInstruction,
  GeneratedNumberBaseFormat as NumberBaseFormat,
  analyzeNumberBaseInput,
  bip39EntropyBits,
  bip39PassphraseAutocomplete,
  bip39PassphraseKeyAllowed,
  bip39PassphraseSpaceAllowed,
  bip39PassphraseState,
  cardKeyAllowed,
  cardTranscriptToEntropy,
  diceMethodInfo,
  directCardState,
  directDiceCalculations,
  directDiceInputState,
  directDiceState,
  diceRollsToEntropy,
  entropyToMnemonic,
  EntropyStudioError_Tags,
  formatDiceTranscript,
  hashedCardState,
  hashedDiceState,
  keyDerivationAddressBenchmarkMilliseconds,
  keyDerivationAddressEstimateMilliseconds,
  keyDerivationAdvancedState,
  keyDerivationProjectAdvancedPath,
  keyDerivationVisiblePathState,
  lifehashFromFingerprint,
  mnemonicToEntropy,
  mnemonicToMasterFingerprint,
  mnemonicToMasterXprv,
  mnemonicToSeed,
  normalizeCardToken,
  normalizeDirectCardTranscript,
  numberBaseCalculations,
  numberBaseEntropy,
  privateKeyEntropy,
  privateKeyInputState,
  privateKeyKeyAllowed,
  privateKeyMaterial,
  seedPhraseAutocomplete,
  seedPhraseKeyAllowed,
  seedPhraseNumbersToWords,
  seedPhraseSpaceAllowed,
  seedPhraseState,
  seedPhraseWordsToNumbers,
  seedQrData,
  synchronizeEntropy,
  translateSeedNumberIndices,
};

export type {
  Bip39PassphraseState,
  DiceMethodInfo,
  DirectCardState,
  DirectDiceCalculationRow,
  DirectDiceState,
  EntropySyncSnapshot,
  HashedCardState,
  HashedDiceState,
  KeyDerivationAdvancedInput,
  KeyDerivationAdvancedState,
  KeyDerivationPathComponent,
  KeyDerivationPathProjectionInput,
  KeyDerivationPathProjectionState,
  KeyDerivationBranch,
  KeyDerivationBranchWindowState,
  KeyDerivationAddressWindowState,
  KeyDerivationIndexState,
  KeyDerivationRangeState,
  KeyDerivationVisiblePathInput,
  KeyDerivationVisiblePathState,
  NumberBaseAnalysis,
  NumberBaseCalculations,
  PrivateKeyInputState,
  PrivateKeyMaterial,
  SeedPhraseAutocompleteResult,
  SeedQrData,
  SeedPhraseState,
} from 'entropystudio';
